### ISSUE TITLE
what is the standard tricks in glue benchmark?

### ISSUE THREAD

**Issue by RyanHuangNLP** [google-research/electra#1]
what is the standard tricks in glue benchmark that achieve +4.2 acc than the electra large?

**Comment by ViktorAlm** [comment]
Theres a slide from Thomas Wolf at HuggingFace Inc. who mentions some of them here:
https://docs.google.com/presentation/d/1LsUAhR_qIVbq6xH6Aw4ag8MGB_-UWfd0KoVhtTgye6o/edit#slide=id.g7cf7e87bbe_1_488 Slide nr.20

But what the electra team did I do not know.

**Comment by clarkkev** [comment]
Hi, the tricks are listed at the end of Appendix B in [the paper](https://openreview.net/pdf?id=r1xMH1BtvB). Essentially (1) [MNLI intermediate training](https://arxiv.org/pdf/1811.01088.pdf) for RTE and STS, (2) Task-specific WNLI classifier (not in the codebase currently, but we will add it later), and (3) Dev-set model selection + ensembling. Many GLUE leaderboard entries use these tricks.
