### ISSUE TITLE
what should i do to extract the electra discriminator 

### ISSUE THREAD

**Issue by mmx1997** [google-research/electra#119]
I have pre-trained the electra model based on the original code **_run_pretraining.py_**, but I found that the generator and discriminator are stored in a ckpt, so what should I do to extract the electra discriminator in the ckpt

**Comment by PhilipMay** [comment]
See here: https://github.com/huggingface/transformers/blob/d5d7d886128732091e92afff7fcb3e094c71a7ec/src/transformers/convert_electra_original_tf_checkpoint_to_pytorch.py

Good luck
Philip

**Comment by mmx1997** [comment]
thank u very much！！！！！！！！
