### ISSUE TITLE
TPU training

### ISSUE THREAD

**Issue by DevKretov** [google-research/electra#12]
Hello, I was wondering whether it is possible to train ELECTRA model on cloud TPUs since you didn't mention TPUs in your research paper. By following this tutorial based on BERT pre-training and fine-tuning on Google Cloud TPUs, I found out some kind of troubles while working in a TPU environment. Here is the link to the BERT TPU tutorial: https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/bert_finetuning_with_cloud_tpus.ipynb

The Colab Notebook I've created from the aforementioned one is here:
https://colab.research.google.com/drive/1ZG8xwXSJm8iQe19M4lACUcCetjf-eZii

The last cell was intended to run training script with use_tpu option flag specified. However, it had no success.

So, am I doing anything wrong or this is a bug on your side?

Thank for your help!

**Comment by stefan-it** [comment]
Yes, it is possible.

You just need to adjust some parameters in the `configure_pretraining.py`.

Mainly, the following parameters should be adjusted:

```python
self.use_tpu = True
self.num_tpu_cores = 8
self.tpu_name = "<your-tpu-name>" 
```

Additionally, you need to copy the tfrecords to a Google Bucket. Then you should able to run pre-training with:

```bash
$ python3 run_pretraining.py --data-dir gs://<bucket-name> --model-name electra-<model-name>
```

(Also make sure, that you've adjusted the `self.pretrain_tfrecords` variable to match the folder structure for your bucket.

**Comment by DayuanJiang** [comment]
In addition, `tpu_name` means `YOUR_TPU_ADDRESS`.   
And I find a great colab notebook for fine-tuning electra using TPU.
https://colab.research.google.com/drive/1WZcZ3hbR-Xh4R5Jv8MWB4ujuX1Ml9KqH
