### ISSUE TITLE
ELECTRA-base fine tuned on MNLI

### ISSUE THREAD

**Issue by ngoquanghuy99** [google-research/electra#120]
Could you please release the ELECTRA-base fine tuned on MNLI or post it on Huggingface's Transformers?

**Comment by PhilipMay** [comment]
If you want to compute an semantic embedding and use cos. similarity -> maybe you want to have a look at this: https://huggingface.co/T-Systems-onsite/cross-en-de-roberta-sentence-transformer

It is very good for English and German. More languages here: https://github.com/German-NLP-Group/xlsr#models
