### ISSUE TITLE
Train electra with another tokenizer

### ISSUE THREAD

**Issue by upskyy** [google-research/electra#127]
## Question

Hello! 
Thanks for providing a good repo.

I think that the official electra code uses wordpiece tokenizer.
but, is it possible to train using another tokenizer?

**Comment by PhilipMay** [comment]
> ## Question
> 
> Hello!
> Thanks for providing a good repo.
> 
> I think that the official electra code uses wordpiece tokenizer.
> but, is it possible to train using another tokenizer?

It should be possible. The model just expects integers...

**Comment by upskyy** [comment]
I checked the model and it was possible. Thank you for the reply.
