### ISSUE TITLE
Will the Pre-trained ELECTRA-1.75M be released?

### ISSUE THREAD

**Issue by xf05888** [google-research/electra#17]
In the paper, it also described a model called ELECTRA-1.75M and has a better performance than ELECTRA-1.45M ( ELECTRA-large ). 
So will the pre-trained  ELECTRA-1.75M  be released?

**Comment by vprelovac** [comment]
It looks like a typo, 1.45M is never mentioned in the paper.

**Comment by xf05888** [comment]
@vprelovac According to README.md, 

> The models were trained on uncased English text. They correspond to ELECTRA-Small++, ELECTRA-Base++, ELECTRA-1.45M in our paper. 

And in the paper it mentioned ELECTRA-Large which is same as ELECTRA-1.45M

Also,
We therefore also report resultsfor ELECTRA-1.75M with the only trick being dev-set model

**Comment by clarkkev** [comment]
Yes, that is a typo!
