### ISSUE TITLE
Load model in Pytorch.

### ISSUE THREAD

**Issue by loopdigga96** [google-research/electra#19]
Hi! Thanks for making source code available and for great paper.

Are there any plans to support loading models in Pytorch?  Or implementation in  [transformers](https://github.com/huggingface/transformers)  by Huggingface?

**Comment by lonePatient** [comment]
@loopdigga96  hi you can try https://github.com/lonePatient/electra_pytorch

**Comment by loopdigga96** [comment]
Thanks!

**Comment by julien-c** [comment]
https://github.com/huggingface/transformers/pull/3257 will land in `master` soon, @loopdigga96

**Comment by Palang2014** [comment]
@julien-c would it support pretraining using electra in huggingface as well or it is just loading the pretrained electra models?

Thanks,
-Hamid

**Comment by julien-c** [comment]
@lysandrejik is working on implementing the ELECTRA pretraining method but that will be in a second PR.

**Comment by clarkkev** [comment]
ELECTRA is now available in PyTorch through the HuggingFace Transformers library! https://github.com/huggingface/transformers/releases/tag/v2.8.0
