### ISSUE TITLE
about chinese model

### ISSUE THREAD

**Issue by Fan9** [google-research/electra#21]
hi, where can i find the pretrained model for chinese text.

**Comment by lonePatient** [comment]
@Fan9 https://github.com/CLUEbenchmark/ELECTRA

**Comment by ymcui** [comment]
We are working on Chinese ELECTRA models, and hopefully it will be available very soon :)
https://github.com/ymcui/Chinese-ELECTRA

**Comment by Fan9** [comment]
@ymcui @lonePatient thinks for your reply.it's very helpful
