### ISSUE TITLE
Continue pretraining on custom dataset

### ISSUE THREAD

**Issue by ViktorAlm** [google-research/electra#25]
First of all very nice work! I love the idea with a discriminator and that the current model architectures is even more capable if its given a more difficult pretraining task.

Unfortunately I think I have to bother you with a problem. I was planning to continue pretraining on the models with domain specific data for some experiments but it seems like the discriminator is not in the released models.  

`raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: From /job:worker/replica:0/task:0:
Key discriminator_predictions/dense/bias/adam_m not found in checkpoint
         [[node save/RestoreV2 (defined at tensorflow_core/python/framework/ops.py:1748) ]]
`

(unrelated)
A 60k test run on the cord19 dataset with eval:
https://tensorboard.dev/experiment/QwOMXKluQJKcn8D9i9p69A/#scalars

**Comment by DayuanJiang** [comment]
@ViktorAlm Dis you solved this problem? I am encountering the same issue.

**Comment by ViktorAlm** [comment]
The necessary inputs from the training is not in the files, you would have to load the weights in from another checkpoint with everything in it or something. I'm not not sure exactly how, it was just an experiment on my part so it wasnt that much of an issue for me. I'm just speculating though.

**Comment by hyusterr** [comment]
@clarkkev I suffer similar problem here, do i have to specify checkpoint or something? electra-small can't continue as you mentioned in readme.
thanks in advanced, here is my command
`python3 run_pretraining.py --data-dir ori-vocab-data-mda --model-name electra_small --hparams '{"model_size": "small", "num_train_steps": 4020000, "electra_objective": true, "vocab_file": "ori-vocab.txt", "learning_rate": 1e-1, "train_batch_size": 128, "generator_hidden_size": 1.0}'
date`
