### ISSUE TITLE
multi-task training

### ISSUE THREAD

**Issue by xiaoxuesheng1234** [google-research/electra#30]
What if I want to Finetune ELECTRA on both classification and sequence tags?
What should i do？

**Comment by clarkkev** [comment]
This is pretty untested but I believe it should be as simple as passing two task names to the `hparams` (e.g., `python3 run_finetuning.py --data-dir $DATA_DIR --model-name electra_base --hparams '{"model_size": "base", "task_names": ["sst", "chunk]}'`)
