### ISSUE TITLE
Auto loading in huggingface Transformers is broken

### ISSUE THREAD

**Issue by xhlulu** [google-research/electra#32]
When I try to load the model following [the instructions](https://huggingface.co/google/electra-small-discriminator) on huggingface.co/models, i.e.:

```python
tokenizer = AutoTokenizer.from_pretrained("google/electra-small-generator")
```

I get the following error:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-bb330c08e050> in <module>
----> 1 tokenizer = AutoTokenizer.from_pretrained("google/electra-small-generator")

/opt/conda/lib/python3.6/site-packages/transformers/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    179         config = kwargs.pop("config", None)
    180         if not isinstance(config, PretrainedConfig):
--> 181             config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
    182 
    183         if "bert-base-japanese" in pretrained_model_name_or_path:

/opt/conda/lib/python3.6/site-packages/transformers/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    185 
    186         if "model_type" in config_dict:
--> 187             config_class = CONFIG_MAPPING[config_dict["model_type"]]
    188             return config_class.from_dict(config_dict, **kwargs)
    189         else:

KeyError: 'electra'
```

The version of transformers is 2.7.0.  I reproduced the problem in [colab here](https://colab.research.google.com/drive/1UmgvYfWvwrFOlf1E7APZOQrUKlY8PO1E).

**Comment by ViktorAlm** [comment]
Electra isnt in HF transformers yet. see https://github.com/huggingface/transformers/pull/3257

**Comment by LysandreJik** [comment]
Indeed, ELECTRA will be merged in the coming days but it is not currently on master yet.

**Comment by julien-c** [comment]
We'll add a "draft" label to the model pages so that it's clearer which models can or cannot be actually loaded from `master` in `transformers`

**Comment by 008karan** [comment]
I saw that [there](https://huggingface.co/models?search=electra-base) are base generators and discriminator models present on HF and not the only electra-base model (which is given in this repo) Getting confused what's difference between them. @xhlulu any idea

**Comment by xhlulu** [comment]
@008karan They are available, but not current usable. The paper goes on detail, but in general you will only need the discriminator for finetuning.

@julien-c I'll keep track of the release on the other issue, thanks for mentioning it! I'll close this for now, and if there's any problem I could reopen this issue (or comment on the other one).

**Comment by 008karan** [comment]
@xhlulu I am looking for pre-training using Electra. I think the generator is required for it. HF is still needed to add the script for pretraining I guess
