### ISSUE TITLE
SQuAD2 Score ELECTRA-Base

### ISSUE THREAD

**Issue by volker42maru** [google-research/electra#33]
Hi there, 

great work on reducing training times!

I was wondering if the reported SQuAD 2.0 results for ELECTRA-Base on this repo are correct: 83.7 EM. This seems to strongly diverge from the reported results in the paper 80.5 EM.

Or is the reported score here meant to be F1?

Cheers

**Comment by clarkkev** [comment]
Thanks for pointing that out! It was a mistake in the documentation and should now be fixed.

**Comment by volker42maru** [comment]
I don't mean to cause any confusion, but when I fine-tuned ELECTRA-Base on squad2 using the code from this repo, I get the following score on the dev set:
```
{
  "exact": 82.58232965552094,
  "f1": 85.48856186236121,
  "total": 11873,
  "HasAns_exact": 82.23684210526316,
  "HasAns_f1": 88.05764085556963,
  "HasAns_total": 5928,
  "NoAns_exact": 82.92682926829268,
  "NoAns_f1": 82.92682926829268,
  "NoAns_total": 5945,
  "best_exact": 83.87939021308853,
  "best_exact_thresh": -2.694678783416748,
  "best_f1": 86.56855327539682,
  "best_f1_thresh": -2.053539991378784
}
```

If this is correct it would mean the reported score in the paper is false/obsolete?
