### ISSUE TITLE
Init disc/generator from pre-trained BERT

### ISSUE THREAD

**Issue by volker42maru** [google-research/electra#38]
Hi there,

in the paper I noticed that you tried training the generator ahead of the discriminator, then initializing the discriminator from the generator weights and train only the discriminator subsequently.

I was wondering, if you also tried the same procedure but instead of training the generator you just initialized both generator and discriminator from a fully MLM pre-trained BERT (e.g. BERT-Large).

Sorry if something was mentioned in the paper and I missed it.

Cheers

**Comment by clarkkev** [comment]
Hi! We never tried exactly that, but it would be pretty much the same as what we did because the generator is essentially the same as BERT. So the experiment in the paper is doing exactly what you are saying but with a BERT-Base model we trained ourselves.
