### ISSUE TITLE
'adam_m not found in checkpoint ' when further pretraining

### ISSUE THREAD

**Issue by DayuanJiang** [google-research/electra#45]
When I was trying further pretraining on the models with domain-specific data in Colab, I encountered a problem that the official pretrained model could not be loaded. 

Here is the commend for further pretraining.

```
hparam =    '{"model_size": "small", \
             "use_tpu":true, \
             "num_tpu_cores":8, \
             "tpu_name":"grpc://10.53.161.26:8470", \
             "num_train_steps":4000100,\
             "pretrain_tfrecords":"gs://tweet_torch/electra/electra/data/pretrain_tf_records/pretrain_data.tfrecord*", \
             "model_dir":"gs://tweet_torch/electra/electra/data/electra_small/", \
             "generator_hidden_size":1.0\
            }'
!python electra/run_pretraining.py  \
                    --data-dir "gs://tweet_torch/electra/electra/data/" \
                    --model-name "electra_small" \
                    --hparams '{hparam}'
```

And the error message is pretty long so I just paste some of it that seems useful.
```python3
ERROR:tensorflow:Error recorded from training_loop: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
From /job:worker/replica:0/task:0:
Key discriminator_predictions/dense/bias/adam_m not found in checkpoint
	 [[node save/RestoreV2 (defined at /tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]

```

**Comment by NLPPower** [comment]
seriously, this problem need to be fixed. I have a similar problem which makes it impossible to recover if the tpu shutdown or I decided to continue my pre-training process.  This needs to be fixed as soon as possible. otherwise, you may pre-train your model for couple of days, and for some reason, you will shut down and you will lose all your work. This should be fixed because it may cost some folks a couple of thousand of dollars to pre-train the model.

**Comment by pnhuy** [comment]
I also had the same problem.

It seems that the adam_m parameter was removed from the checkpoint before saving. (https://github.com/google-research/bert/issues/99#issuecomment-442069063)

So if we don't have the full checkpoint, we can't do further training.

Just waiting for the full checkpoint.

**Comment by clarkkev** [comment]
You should be able to do further training, just don't initialize the Adam parameters from the checkpoint by doing something like [this](https://github.com/google-research/electra/blob/79111328070e491b287c307906701ebc61091eb2/run_finetuning.py#L87). I don't think refreshing the Adam parameters will cause any real problem with the model.

**Comment by w5688414** [comment]
I meet the same problem

**Comment by Lincoln-Jiang** [comment]
Hello, I checked the solution @clarkkev mentioned above but still don't know the exact solution. Can anyone provide any further help? I am new to tensorflow and did not find anywhere skip the adam_m parameters from the link above. Thank you in advance.

**Comment by Veyronl** [comment]
I have the same trouble.Could you tell me how to fix it? @clarkkev @Lincoln-Jiang @w5688414 Thank you in advance.

**Comment by DayuanJiang** [comment]
@Veyronl  I just gave up using Electra.
