### ISSUE TITLE
Build Dataset Issue

### ISSUE THREAD

**Issue by qute012** [google-research/electra#46]
https://github.com/google-research/electra/blob/62e478a6353c7217c166582f49bca55c0de96a8d/build_pretraining_dataset.py#L53

Is _current_length bigger than _target_length(max_seq_length)?
I think it should be the other way around.

**Comment by clarkkev** [comment]
I think this is correct. We keep adding sentences to the current example until we go over length, in which case we then write out the example as a tfrecord and start building a new example.
