### ISSUE TITLE
Low usage of gpu

### ISSUE THREAD

**Issue by amy-hyunji** [google-research/electra#48]
I tried pretraining for small, base, large model on one 2080 Ti gpu but it seems like there is very low usage of gpu. Am I doing something wrong or is the usage of gpu actually low?

**Comment by icoffeebeans** [comment]
Hi @amy-hyunji I'm also facing lower usage of GPU memory when do fine-tuning. Have you solve this problem?

**Comment by amy-hyunji** [comment]
hi, it was due to tf version. Try to check if your version is right
