### ISSUE TITLE
BasicTokenizer: _run_strip_accents

### ISSUE THREAD

**Issue by Vodolazskyi** [google-research/electra#52]
Hello,

I noticed that `BasicTokenizer` runs `_run_strip_accents` by default and it's not parameterizable. Is it critical for training Electra? Is it OK to turn it off for training non-English models?

Thanks.

**Comment by clarkkev** [comment]
I don't think it is critical. We just used the same tokenization as BERT, which included the `_run_strip_accents` text normalization.
