### ISSUE TITLE
Question about layerwise learning rate decay

### ISSUE THREAD

**Issue by TianyuZhuuu** [google-research/electra#64]
Hi @clarkkev ,

I am confused with the implementation of layerwise learning rate decay. It seems the depths ranges as `[0, 1, ..., n_layers-1, n_layers, n_layers+2]`. Why the depth of the task specific layer is set to `n_layers+2` instead of `n_layers+1`? Are there any specific reason for this? 

https://github.com/google-research/electra/blob/79111328070e491b287c307906701ebc61091eb2/model/optimization.py#L181-L193

Cheers

**Comment by clarkkev** [comment]
Hi, this is a small mistake in the code, see https://github.com/google-research/electra/issues/51

**Comment by TianyuZhuuu** [comment]
Thanks!
