### ISSUE TITLE
Training Electra on 2 phases like Bert

### ISSUE THREAD

**Issue by agemagician** [google-research/electra#66]
Bert could be trained in 2 phases. The first phase with shorter length (128) then the second phase with longer length (512). The first phase accelerate training while the second phase makes the positional encoding learn longer sentences.
This does work as long as the "max_position_embeddings" is 512.

Can Electra trained on the same way or since it has a final layer for classifying each token it will not work ?

@clarkkev @stefan-it @mrm8488 @michelole , Your feedback is highly appreciated.

**Comment by agemagician** [comment]
ok, so I tested it and it does work.
Electra could be trained on 2 phases.
1st phase, shorter sequence length.
2nd phase, longer sequence length.
This should accelerate training.

**Comment by santaonchair** [comment]
Hi, @agemagician

I pretrained my model (electra base) on 2 phases but the performance seems worse :/ 
my **max_position_embeddings** was also 512. and below is my training details

**phase1**: trained 1M steps with **max_seq_length**: 128
**phase2**: trained 0.1M - 0.3M steps with **max_seq_length**: 512

I would appreciate it a lot if you share more information about yours 🤝 

thank you

**Comment by mrm8488** [comment]
Hi, did you finally improved your results?

**Comment by santaonchair** [comment]
Hi :) Sorry for the late reply. 

I finally improved my result with `max_seq 512` but when I pretrained my model with `max_seq 1024`. it seems not working.

 `max_position_embeddings`: 1024
 * *phase1*: trained 1M steps with `max_seq 128`, `batch_size 400`
 * *phase2*: trained 0.1M - 0.2M steps with `max_seq 512`, `batch_size 200`
 * *phase3*: trained 0.1M - 0.2M steps with `max_seq 1024`, `batch_size 80` (`phase3` result is way lower than *phase2*)
