### ISSUE TITLE
Is `google/electra-small-generator` small or small++ ?

### ISSUE THREAD

**Issue by richardyy1188** [google-research/electra#68]
Hi, I notice that  the `Electra small` and `Electra base` in GLUE benchmark are `Electra-small++` and `Electra-base++` in table 8.

To correctly compare my reproduced results,
I am wondering whether `google/electra-small-discriminator` and `google/electra-base-discriminator `on Huggingface models hub are also  `Electra-small++` and `Electra-base++` ?

**Comment by clarkkev** [comment]
They are also the ++ models.
