### ISSUE TITLE
Failed to convert object of type <class 'dict'> to Tensor

### ISSUE THREAD

**Issue by lizaigaoge550** [google-research/electra#75]
During i run code, i found some error during training model as per below
Failed to convert object of type <class 'dict'> to Tensor
the error is here in optimization.py and i used tf.1.12
![屏幕快照 2020-06-16 下午5 45 20](https://user-images.githubusercontent.com/12975526/84759387-3dfe1280-aff9-11ea-9546-eebd91cb5984.png)
how can i fix it?

**Comment by stefan-it** [comment]
Hi @lizaigaoge550, could you try to use TensorFlow 1.15 -> I did use that version for training my ELECTRA models and it always worked :)
