### ISSUE TITLE
How can I make ELECTRA pretraining/dataloading use only one gpu ?

### ISSUE THREAD

**Issue by richarddwang** [google-research/electra#86]
I have a 4 gpu server, and I found even I just load data use input_func from `get_input_fn`, it use all my 4 gpus for 305Mib memory space each.

**Comment by anshulsamar** [comment]
@richarddwang Perhaps try setting CUDA_VISIBLE_DEVICES? Or do you still have an issue...

**Comment by richarddwang** [comment]
Thank you, @anshulsamar !
I set `os.environ["CUDA_VISIBLE_DEVICES"] = "3"` and it use just cuda:3

May I ask one more question that not it takes only 305MiB on one GPU (GV100, fast as V100) and the training process is slow (1.1 % after 6hr), I am using default config. Is there any suggestion ?

**Comment by anshulsamar** [comment]
No problem, not sure about that one...
